services:
    influxdb:
        image: influxdb:2.6
        env_file:
          - .env
        restart: always
        volumes:
          - ./influxdb/data:/var/lib/influxdb2
          - ./influxdb/config:/etc/influxdb2
        ports:
          - "8086:8086"
    telegraf:
        build: ./telegraf
        container_name: telegraf
        links:
            - influxdb
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/hostfs/proc
        privileged: true
        restart: always
        env_file:
            - .env
        networks:
            shared: null
    grafana:
        build: ./grafana
        container_name: grafana
        environment:
            GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /opt/grafana/dashboards/Monitoring.json
        ports: 
            - ${GRAFANA_PORT}:${GRAFANA_PORT}
        links:
            - influxdb
        volumes:
            - /var/lib/grafana
            - /var/log/grafana
            - /var/lib/grafana/plugins
            - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
        restart: always
        env_file:
            - .env
        networks:
            shared: null
    loki:
      command: -config.file=/etc/loki/loki-config.yml
      container_name: loki
      image: grafana/loki:2.8.4
      env_file:
          - .env
      networks:
        shared: null
      ports:
      - protocol: tcp
        published: 3100
        target: 3100
      restart: always
      volumes:
      - ./loki/loki-config-filesystem.yml:/etc/loki/loki-config.yml:ro
      - /home/loki/:/home/loki/
    promtail:
      command: -config.file=/etc/promtail/promtail-config.yml
      container_name: promtail
      image: grafana/promtail:2.3.0
      networks:
        shared: null
      ports:
      - protocol: tcp
        published: 1514
        target: 1514
      - protocol: tcp
        published: 9080
        target: 9080
      restart: always
      volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
    syslog-ng:
      command: -edv
      container_name: syslog-ng
      depends_on:
      - promtail
      image: balabit/syslog-ng:latest
      networks:
        shared: null
      ports:
      - protocol: udp
        published: 514
        target: 514
      - protocol: tcp
        published: 601
        target: 601
      restart: always
      volumes:
      - ./syslog-ng/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro

networks:
    shared: {}
