hubble:
  enabled: true
  metrics:
    enabled:
      - drop
      - tcp
      - dns
      - flow
      # https://grafana.com/grafana/plugins/isovalent-hubble-datasource service map
      - httpV2:sourceContext=workload-name|pod-name|reserved-identity;destinationContext=workload-name|pod-name|reserved-identity;labelsContext=source_pod,source_ip,source_namespace,source_workload,destination_pod,destination_ip,destination_namespace,destination_workload,traffic_direction
  relay:
    enabled: true
  # ui:
  #   enabled: true
operator:
  prometheus:
    enabled: true
prometheus:
  enabled: true
