apiVersion: 1
datasources: 
  - 
    access: proxy
    basicAuth: false
    auth_enabled: false
    jsonData: 
      maxLines: 1000
    name: Loki
    type: loki
    url: "http://loki:3100/"
  - 
    access: proxy
    basicAuth: false
    name: Prometheus
    type: prometheus
    url: "http://prometheus:9090/"